version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  # mongodb:
  #   image: mongo
  #   container_name: mongodb
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: testmongo
  #     MONGO_INITDB_ROOT_PASSWORD: testmongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
